language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-27.0.3
    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services

    - sys-img-armeabi-v7a-android-22
    
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-27"

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
   - ./gradlew build connectedCheck --stacktrace
